"use client"

import { useState } from "react"
import { AdminHeader } from "@/components/super-admin-portal/header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { Calendar } from "@/components/ui/calendar"
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover"
import { cn } from "@/lib/utils"
import { format } from "date-fns"
import { CalendarIcon, FileText, Download, FileJson, FileSpreadsheet, File, Eye, Clock, CheckCircle2, AlertTriangle } from "lucide-react"

interface Report {
  id: string
  type: string
  generatedAt: string
  status: "completed" | "processing" | "failed"
  size: string
}

const recentReports: Report[] = [
  { id: "RPT-001", type: "FERPA Compliance Audit", generatedAt: "2024-03-15 14:30", status: "completed", size: "2.4 MB" },
  { id: "RPT-002", type: "User Access Report", generatedAt: "2024-03-15 10:15", status: "completed", size: "1.8 MB" },
  { id: "RPT-003", type: "Blockchain Transaction Log", generatedAt: "2024-03-14 16:45", status: "completed", size: "15.2 MB" },
  { id: "RPT-004", type: "Data Retention Report", generatedAt: "2024-03-14 09:00", status: "processing", size: "-" },
  { id: "RPT-005", type: "System Security Audit", generatedAt: "2024-03-13 11:30", status: "failed", size: "-" },
]

const sampleReportContent = `
================================================================================
                     UNIVERSITY DATA MANAGEMENT SYSTEM
                        COMPLIANCE AUDIT REPORT
================================================================================

Report Type: FERPA Compliance Audit
Generated: March 15, 2024 at 14:30 UTC
Period: March 1, 2024 - March 15, 2024
Generated By: System Administrator

--------------------------------------------------------------------------------
                              EXECUTIVE SUMMARY
--------------------------------------------------------------------------------

Total Records Audited: 45,678
Compliant Records: 45,234 (99.03%)
Non-Compliant Records: 444 (0.97%)
Critical Issues: 3
Warnings: 28

--------------------------------------------------------------------------------
                              ACCESS STATISTICS
--------------------------------------------------------------------------------

Total Data Access Events: 128,456
- Student Records Accessed: 89,234
- Faculty Records Accessed: 24,567
- Credential Verifications: 14,655

Authorized Access: 128,412 (99.97%)
Unauthorized Attempts: 44 (0.03%)

--------------------------------------------------------------------------------
                              BLOCKCHAIN INTEGRITY
--------------------------------------------------------------------------------

Student Blockchain:
  - Total Blocks: 1,234,567
  - Verified Blocks: 1,234,567 (100%)
  - Hash Integrity: PASSED
  - Merkle Root Verification: PASSED

Faculty Blockchain:
  - Total Blocks: 987,654
  - Verified Blocks: 987,654 (100%)
  - Hash Integrity: PASSED
  - Merkle Root Verification: PASSED

Institutional Blockchain:
  - Total Blocks: 654,321
  - Verified Blocks: 654,321 (100%)
  - Hash Integrity: PASSED
  - Merkle Root Verification: PASSED

--------------------------------------------------------------------------------
                              DATA PROTECTION
--------------------------------------------------------------------------------

Encryption Status:
  - Data at Rest: AES-256 (COMPLIANT)
  - Data in Transit: TLS 1.3 (COMPLIANT)
  - Key Rotation: Every 30 days (COMPLIANT)

PII Handling:
  - Masked Fields: 12,456
  - Tokenized Records: 34,567
  - Anonymized Exports: 156

--------------------------------------------------------------------------------
                              RECOMMENDATIONS
--------------------------------------------------------------------------------

1. [CRITICAL] Review and resolve 3 unauthorized access patterns
2. [WARNING] Update consent forms for 28 student records
3. [INFO] Consider increasing audit log retention period
4. [INFO] Schedule quarterly penetration testing

--------------------------------------------------------------------------------
                              CERTIFICATION
--------------------------------------------------------------------------------

This report certifies that the University Data Management System has been
audited for FERPA compliance according to the standards set forth in
34 CFR Part 99.

Audit Conducted By: Automated Compliance Engine v2.1.0
Validation Hash: 0x8f4e3a2b...9c1d7e5f

================================================================================
                              END OF REPORT
================================================================================
`

export default function CompliancePage() {
  const [reportType, setReportType] = useState("ferpa")
  const [startDate, setStartDate] = useState<Date>()
  const [endDate, setEndDate] = useState<Date>()
  const [showPreview, setShowPreview] = useState(false)

  return (
    <div className="min-h-screen">
      <AdminHeader title="Compliance & Audit Reports" code="ADM-08" />
      <main className="p-6 space-y-6">
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          {/* Report Generator */}
          <Card className="bg-card border-border lg:col-span-1">
            <CardHeader>
              <CardTitle className="font-serif text-base flex items-center gap-2">
                <FileText className="h-5 w-5 text-primary" />
                Generate Report
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-2">
                <Label>Report Type</Label>
                <Select value={reportType} onValueChange={setReportType}>
                  <SelectTrigger className="bg-muted border-border">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="ferpa">FERPA Compliance Audit</SelectItem>
                    <SelectItem value="gdpr">GDPR Compliance Report</SelectItem>
                    <SelectItem value="access">User Access Report</SelectItem>
                    <SelectItem value="blockchain">Blockchain Transaction Log</SelectItem>
                    <SelectItem value="retention">Data Retention Report</SelectItem>
                    <SelectItem value="security">System Security Audit</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="space-y-2">
                <Label>Start Date</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      className={cn(
                        "w-full justify-start text-left font-normal bg-muted border-border",
                        !startDate && "text-muted-foreground"
                      )}
                    >
                      <CalendarIcon className="mr-2 h-4 w-4" />
                      {startDate ? format(startDate, "PPP") : "Select start date"}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-auto p-0" align="start">
                    <Calendar
                      mode="single"
                      selected={startDate}
                      onSelect={setStartDate}
                      initialFocus
                    />
                  </PopoverContent>
                </Popover>
              </div>

              <div className="space-y-2">
                <Label>End Date</Label>
                <Popover>
                  <PopoverTrigger asChild>
                    <Button
                      variant="outline"
                      className={cn(
                        "w-full justify-start text-left font-normal bg-muted border-border",
                        !endDate && "text-muted-foreground"
                      )}
                    >
                      <CalendarIcon className="mr-2 h-4 w-4" />
                      {endDate ? format(endDate, "PPP") : "Select end date"}
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="w-auto p-0" align="start">
                    <Calendar
                      mode="single"
                      selected={endDate}
                      onSelect={setEndDate}
                      initialFocus
                    />
                  </PopoverContent>
                </Popover>
              </div>

              <div className="pt-4 space-y-2">
                <Button 
                  className="w-full bg-primary hover:bg-primary/90 gap-2"
                  onClick={() => setShowPreview(true)}
                >
                  <Eye className="h-4 w-4" />
                  Generate & Preview
                </Button>
              </div>

              <div className="pt-2">
                <Label className="text-muted-foreground text-xs">Export Format</Label>
                <div className="grid grid-cols-3 gap-2 mt-2">
                  <Button variant="outline" size="sm" className="gap-1">
                    <File className="h-4 w-4 text-error" />
                    PDF
                  </Button>
                  <Button variant="outline" size="sm" className="gap-1">
                    <FileSpreadsheet className="h-4 w-4 text-success" />
                    CSV
                  </Button>
                  <Button variant="outline" size="sm" className="gap-1">
                    <FileJson className="h-4 w-4 text-secondary" />
                    JSON
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Report Preview */}
          <Card className="bg-card border-border lg:col-span-2">
            <CardHeader>
              <CardTitle className="font-serif text-base flex items-center gap-2">
                <Eye className="h-5 w-5 text-secondary" />
                Report Preview
              </CardTitle>
            </CardHeader>
            <CardContent>
              {showPreview ? (
                <div className="rounded-lg bg-[#0D1117] p-4 h-[500px] overflow-auto">
                  <pre className="font-mono text-xs text-gray-300 whitespace-pre-wrap">
                    {sampleReportContent}
                  </pre>
                </div>
              ) : (
                <div className="flex items-center justify-center h-[500px] rounded-lg border border-dashed border-border">
                  <div className="text-center">
                    <FileText className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                    <p className="text-muted-foreground">
                      Select report options and click Generate to preview
                    </p>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>

        {/* Recent Reports */}
        <Card className="bg-card border-border">
          <CardHeader>
            <CardTitle className="font-serif text-base flex items-center gap-2">
              <Clock className="h-5 w-5 text-info" />
              Recent Reports
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {recentReports.map((report) => (
                <div
                  key={report.id}
                  className="flex items-center justify-between rounded-lg border border-border bg-muted/50 p-4"
                >
                  <div className="flex items-center gap-4">
                    <div
                      className={cn(
                        "flex h-10 w-10 items-center justify-center rounded-lg",
                        report.status === "completed"
                          ? "bg-success/10"
                          : report.status === "processing"
                          ? "bg-warning/10"
                          : "bg-error/10"
                      )}
                    >
                      {report.status === "completed" ? (
                        <CheckCircle2 className="h-5 w-5 text-success" />
                      ) : report.status === "processing" ? (
                        <Clock className="h-5 w-5 text-warning animate-pulse" />
                      ) : (
                        <AlertTriangle className="h-5 w-5 text-error" />
                      )}
                    </div>
                    <div>
                      <p className="font-medium">{report.type}</p>
                      <div className="flex items-center gap-3 text-xs text-muted-foreground">
                        <span className="font-mono">{report.id}</span>
                        <span>{report.generatedAt}</span>
                        {report.size !== "-" && <span>{report.size}</span>}
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {report.status === "completed" && (
                      <>
                        <Button variant="ghost" size="sm" className="gap-1">
                          <Eye className="h-4 w-4" />
                          View
                        </Button>
                        <Button variant="ghost" size="sm" className="gap-1">
                          <Download className="h-4 w-4" />
                          Download
                        </Button>
                      </>
                    )}
                    {report.status === "processing" && (
                      <span className="text-xs text-warning">Processing...</span>
                    )}
                    {report.status === "failed" && (
                      <Button variant="ghost" size="sm" className="text-error gap-1">
                        Retry
                      </Button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}
